import { CartProvider } from "./context/CartContext";

export const metadata = {
  title: "Hardware Tools Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
         <CartProvider>{children}</CartProvider>
      </body>
    </html>
  );
}
